### ISSUE TITLE
Create文（DBへのテーブル作成用）を書く

### ISSUE THREAD

**Issue by ms2sato** [Fuluha/PriceResearcher#2]
ref #1 
- 新規データベースを作る
- Create文を書く（テキスト）
- 作成できたらクリア

**Comment by ms2sato** [comment]
例:
- cards_development
- cards_production

**Comment by Fuluha** [comment]
CREATE TABLE cards_development (
	name varchar NOT NULL,
	attack int NOT NULL,
	defense int NOT NULL,
	serial_number varchar NOT NULL,
);

**Comment by ms2sato** [comment]
@Fuluha VeryGood!この内容を create.sql という名前でファイルに保存して、gitでpushしてくださーい。

あ、テーブル名は `cards` ですね。
データベースは複数のテーブルを束ねる存在なので、もう一段大きな集合です。データベース名はサービス名にするイメージを伝えられてなかった。ごめんなさい。

情報の単位的には以下のような雰囲気になる感じです。

- yuugiou_development（データベース）
  - cards（テーブル）
    - name（カラム）
    - attack（カラム）
  - tags（テーブル）

下記など参考になるかと。
https://www.dbonline.jp/phpmyadmin/database/index1.html

**Comment by Fuluha** [comment]
[create.sql.zip](https://github.com/Fuluha/PriceResearcher/files/3413266/create.sql.zip)

**Comment by ms2sato** [comment]
https://github.com/Fuluha/PriceResearcher
ここの画面に入るように、SourceTreeを使ってファイルを追加して、git のpush を行いましょう。
できるかな？

**Comment by Fuluha** [comment]
失礼しました。
これから習慣を作っていきます。
プッシュしました。

**Comment by ms2sato** [comment]
@Fuluha OKです！今後はファイルのインデントにも気を配っていきましょう。以下のような感じで親子関係を左側のスペースで示します。

```
CREATE TABLE cards_development (
  name varchar NOT NULL,
  attack int NOT NULL,
  defense int NOT NULL,
  serial_number varchar NOT NULL,
);
```

**Comment by ms2sato** [comment]
大丈夫なのでCloseです。
