### ISSUE TITLE
DBへのInsertを調べる

### ISSUE THREAD

**Issue by ms2sato** [Fuluha/PriceResearcher#3]
PHP MyAdmin上でやりましょう。
- Insert文を書く

「SQL Insert」くらいで調べると情報がヒットすると思います。

**Comment by ms2sato** [comment]
@Fuluha InsertできたSQLをここに書いて教えてください。

**Comment by Fuluha** [comment]
実行文を書くという解釈でよろしかったでしょうか？
その場合こちらになります。
ご確認お願いします。

INSERT INTO cards (
　name,
    attack,
    defense,
    serial_number
)
VALUES(
    'セイクリッド・プレアデス',
    '2500',
    '1500',
    '73964868'
)

**Comment by ms2sato** [comment]
@Fuluha 大丈夫そうですね！

**Comment by ms2sato** [comment]
このIssueは見直したくなるかもしれないので一旦このままにしますが、他のIssueは並行して進められると思うので、 #5、 #4 と進めてみてくださーい。
