### ISSUE TITLE
DBへの接続をしてデータを取得しましょう

### ISSUE THREAD

**Issue by ms2sato** [Fuluha/PriceResearcher#4]
先に #5 をやってみてください。 Select文を書いてみましょう。

PDOを利用した SELECT文を調べる

- DBへの接続
  - 深い理解は後で大丈夫です
- SELECT文の発行
- 画面になにか出す

**Comment by Fuluha** [comment]
![スクリーンショット 2019-07-23 23 02 06](https://user-images.githubusercontent.com/34618437/61718456-00b7e300-ad9e-11e9-9ffc-fe20a64c383f.png)
無事に表示できました！

**Comment by ms2sato** [comment]
バッチリです！対面でフォローしまーす。
