### ISSUE TITLE
[php]DBへ接続して、insertする

### ISSUE THREAD

**Issue by ms2sato** [Fuluha/PriceResearcher#6]
#4 でSELECTができたと思うので、別のファイルに今度はINSERTを作成してみましょう。
一旦PHPから行えれば大丈夫です。これらをどのようにWEBの画面に整理するのかは対面でやるとスムーズだと考えています。

**Comment by Fuluha** [comment]
![スクリーンショット 2019-07-24 20 37 30](https://user-images.githubusercontent.com/34618437/61790751-058a9e80-ae53-11e9-9a47-59d4cf82c33c.png)
無事にPHPでINSERT文を書いてDBに格納しました。
試しにもう1回実行してみたら2重に入ったので、PHPで削除できないか調べてみます。
