### ISSUE TITLE
[php]一覧画面を整える

### ISSUE THREAD

**Issue by ms2sato** [Fuluha/PriceResearcher#7]
ファイル名: index.php
結果: HTMLのテーブルタグで、DB内の全カード情報が一覧できること

HTMLとしての画面を整えるIssueになります。デザインに凝らなくて大丈夫なので、テーブルタグで表示できればクリアです！

**Comment by Fuluha** [comment]
![スクリーンショット 2019-07-26 0 17 15](https://user-images.githubusercontent.com/34618437/61886783-4e1d8700-af3b-11e9-880b-c496fa64833a.png)
途中「MAMPが表示されない」「HTMLでの表示うまくいかない」などがありましたが、無事に表示できました！

**Comment by ms2sato** [comment]
@Fuluha バッチリです！よくできていまーす。
