### ISSUE TITLE
[php]DB接続処理を関数にして共通のファイルにする

### ISSUE THREAD

**Issue by ms2sato** [Fuluha/PriceResearcher#8]
DB接続はほぼ全てのPHPで利用可能だと思うので、関数にして使い回せるようにしましょう。以下2点がキーワードです。

- require
- phpの関数

**Comment by Fuluha** [comment]
DB接続の部分を「config.php」に入れて表示部分を「core.php」としてあげました。
ご確認お願いします。
この宣言方法などもご教授頂ければと思います。
